
import dao.ConnectionProvider;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author prems
 */
public class AddMaterial extends javax.swing.JFrame {

    /**
     * Creates new form AddMaterial
     */
    
    private int materialId = 0;
    private String vendorId = "";
    
    public AddMaterial() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private boolean validateFields() {
        if (!txtMaterialId.equals("") && !txtMaterialName.equals("") && !txtDescription.equals("") && !txtQuantity.equals("") && !txtPrice.equals("") && !vendorId.equals("") ) {
            return false;
        } else {
            return true;
        }
    }
    
//    private void clearSelectedVendor(){
//        vendorId = 0;
//        txtVendorName.setText("");
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        materialTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaterialId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMaterialName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vendorTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        addVendorBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtVendorName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtVendorId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        materialTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Material Id", "Material name", "Description", "Quantity", "Price", "Vendor Id", "Product Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        materialTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                materialTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(materialTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 124, 417, 732));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Enter Details");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 124, -1, -1));

        jLabel1.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel1.setText("Add Material");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 16, -1, -1));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel5.setText("Material Id");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 190, -1, -1));
        getContentPane().add(txtMaterialId, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 218, 267, -1));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel6.setText("Material name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 252, -1, -1));
        getContentPane().add(txtMaterialName, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 280, 267, -1));

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel8.setText("Description");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 320, -1, -1));
        getContentPane().add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 348, 267, -1));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel7.setText("Quantity");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 382, -1, -1));
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 410, 267, -1));

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel9.setText("Price");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 450, -1, -1));
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 478, 267, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Materials");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 93, -1, -1));

        vendorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vendor Id", "Vendor name", "Phone number"
            }
        ));
        vendorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vendorTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(vendorTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(919, 124, -1, 732));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Vendors");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, -1, -1));

        addVendorBtn.setBackground(new java.awt.Color(0, 153, 255));
        addVendorBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addVendorBtn.setText("Add Vendor");
        addVendorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVendorBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addVendorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 90, -1, -1));

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 549, 267, -1));

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 590, -1, -1));

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 590, -1, -1));

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, -1, -1));

        jLabel4.setText("Selected Vendor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 654, -1, -1));
        getContentPane().add(txtVendorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 784, 267, -1));

        jLabel11.setText("Vendor Id");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 688, -1, -1));

        jLabel12.setText("Vendor name");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 756, -1, -1));
        getContentPane().add(txtVendorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 728, 267, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 30, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BigBG.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String id = txtMaterialId.getText();
        String name = txtMaterialName.getText();
        String description = txtDescription.getText();
        String quantity = txtQuantity.getText();
        String price = txtPrice.getText();
        
        if(validateFields()){
            JOptionPane.showMessageDialog(null, "Enter all the fields");
        }
        else{
            try{
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("insert into material (Material_id,Material_name,Description,Quantity,Price,MVendor_id, ProductID) values(?,?,?,?,?,?,?);");
                ps.setString(1,id);
                ps.setString(2,name);
                ps.setString(3,description);
                ps.setString(4,quantity);
                ps.setString(5,price);
                ps.setString(6, vendorId);
                ps.setString(7, null);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Material added Successfully");
                setVisible(false);
                new AddMaterial().setVisible(true);
        }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String id = txtMaterialId.getText();
        String name = txtMaterialName.getText();
        String description = txtDescription.getText();
        String quantity = txtQuantity.getText();
        String price = txtPrice.getText();
        String VID  = txtVendorId.getText();
        
       
            try{
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("update material set Material_id = ?,Material_name = ?,Description = ?,Quantity = ?,Price = ?,MVendor_id = ?, ProductID = ? where Material_id = ? ;");
                ps.setString(1,id);
                ps.setString(2,name);
                ps.setString(3,description);
                ps.setString(4,quantity);
                ps.setString(5,price);
                ps.setString(6, VID);
                ps.setString(7, null);
                ps.setString(8,id);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Material updates Successfully");
                setVisible(false);
                new AddMaterial().setVisible(true);
        }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        String id = txtMaterialId.getText();
         try{
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("delete from material where  Material_id=? ");
                ps.setString(1,id);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Material deleted Successfully");
                setVisible(false);
                new AddMaterial().setVisible(true);
        }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddMaterial().setVisible(true);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        txtMaterialId.setEditable(false);
        txtVendorId.setEditable(false);
        txtVendorName.setEditable(false); 
        DefaultTableModel model = (DefaultTableModel) materialTable.getModel();
        DefaultTableModel vendorModel = (DefaultTableModel) vendorTable.getModel();
        
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from material;");
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("Material_id"), rs.getString("Material_name"), rs.getString("Description"), rs.getString("Quantity"), rs.getString("Price"), rs.getString("MVendor_id"),rs.getString("ProductID")});
            }
            
            rs = st.executeQuery("select * from vendor;");
            while(rs.next()){
                vendorModel.addRow(new Object[]{rs.getString("Vendor_id"), rs.getString("Vendor_name"), rs.getString("Phone_number")});
            }
            
            int num=0;
            rs = st.executeQuery("select count(*) as num from material;");
            while(rs.next()){
                num = Integer.parseInt(rs.getString("num"));
            }
            num+=1;
            txtMaterialId.setText("TBM"+num);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e); 
        }
    }//GEN-LAST:event_formComponentShown

    private void vendorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendorTableMouseClicked
        // TODO add your handling code here:
        int index = vendorTable.getSelectedRow();
        TableModel model = vendorTable.getModel();
        String id = model.getValueAt(index, 0).toString();
        vendorId = id;
        txtVendorId.setText(id);
        String name = model.getValueAt(index, 1).toString();
        txtVendorName.setText(name);
        
    }//GEN-LAST:event_vendorTableMouseClicked

    private void addVendorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVendorBtnActionPerformed
        // TODO add your handling code here:
        new ManageVendors().setVisible(true);
    }//GEN-LAST:event_addVendorBtnActionPerformed

    private void materialTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialTableMouseClicked
        // TODO add your handling code here:
        int index = materialTable.getSelectedRow();
        TableModel model = materialTable.getModel();
        String id = model.getValueAt(index, 0).toString();
        txtMaterialId.setText(id);
        String name = model.getValueAt(index, 1).toString();
        txtMaterialName.setText(name);
        String description = model.getValueAt(index, 2).toString();
        
        txtDescription.setText(description);
        String quantity = model.getValueAt(index, 3).toString();
        txtQuantity.setText(quantity);
        String price = model.getValueAt(index, 4).toString();
        txtPrice.setText(price);
        String VID = model.getValueAt(index, 5).toString();
        txtVendorId.setText(VID);
        
        saveBtn.setEnabled(false); 
        updateBtn.setEnabled(true);
        txtVendorName.setEnabled(false);
        resetBtn.setEnabled(true); 
        deleteBtn.setEnabled(true); 
    }//GEN-LAST:event_materialTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVendorBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable materialTable;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtMaterialId;
    private javax.swing.JTextField txtMaterialName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtVendorId;
    private javax.swing.JTextField txtVendorName;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTable vendorTable;
    // End of variables declaration//GEN-END:variables
}
